print("ini latihan github pertama")
print("ini latihan github pertama")
print("ini latihan github pertama")
print("ini latihan github pertama")
print("ini latihan github pertama")
print("ini latihan github pertama")
print("ini latihan github pertama")
print("ini latihan github pertama")
